# Generated by Django 2.1.1 on 2018-09-01 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.DateTimeField(auto_now=True)),
                ('T_boiler', models.FloatField()),
                ('T_amb', models.FloatField(blank=True, null=True)),
                ('duty', models.FloatField(default=0)),
                ('duty_p', models.FloatField(default=0)),
                ('duty_i', models.FloatField(default=0)),
                ('duty_d', models.FloatField(default=0)),
                ('Vdot', models.FloatField(default=0)),
                ('brewing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Schedule', max_length=20)),
                ('days', models.CharField(default='0000000', max_length=7)),
                ('t_on', models.TimeField(default=datetime.time(0, 0))),
                ('t_off', models.TimeField(default=datetime.time(0, 0))),
                ('active', models.BooleanField()),
                ('key_task_on', models.IntegerField(blank=True, null=True)),
                ('key_task_off', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_start', models.DateTimeField(auto_now=True)),
                ('t_end', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_p', models.FloatField(default=0)),
                ('k_d', models.FloatField(default=0)),
                ('k_i', models.FloatField(default=0)),
                ('T_set', models.FloatField(default=95)),
                ('V', models.FloatField(default=200)),
                ('t_update', models.IntegerField(default=5)),
                ('t_sample', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.BooleanField(default=False)),
                ('brew', models.BooleanField(default=False)),
            ],
        ),
    ]
