# Generated by Django 2.1.1 on 2018-09-04 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('silviacontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='t_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
