# Generated by Django 2.1.1 on 2018-09-15 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silviacontrol', '0003_auto_20180905_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemodel',
            name='t_off',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='schedulemodel',
            name='t_on',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
