# Generated by Django 3.0.6 on 2020-05-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
        ('silviacontrol', '0004_auto_20180915_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemodel',
            name='name',
            field=models.CharField(default='Schedule reinvigoration', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='schedule_off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_off', to='django_celery_beat.PeriodicTask'),
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='schedule_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_on', to='django_celery_beat.PeriodicTask'),
        ),
    ]
