# Generated by Django 3.0.6 on 2020-07-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silviacontrol', '0005_auto_20200527_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsemodel',
            old_name='Vdot',
            new_name='m',
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='name',
            field=models.CharField(default='New Schedule', max_length=20),
        ),
    ]
