# Generated by Django 3.0.6 on 2020-07-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silviacontrol', '0007_auto_20200707_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsemodel',
            old_name='T_amb',
            new_name='T_setpoint',
        ),
    ]
