# Generated by Django 3.0.6 on 2020-07-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silviacontrol', '0009_auto_20200711_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsemodel',
            name='low_water',
            field=models.BooleanField(default=False),
        ),
    ]
