# Generated by Django 3.0.6 on 2020-08-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silviacontrol', '0011_auto_20200819_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsemodel',
            name='k_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='k_i',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='k_p',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
