# Generated by Django 3.0.6 on 2020-09-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silviacontrol', '0012_auto_20200819_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='k_p_mode',
            field=models.IntegerField(default=1),
        ),
    ]
