# Generated by Django 3.0.6 on 2020-10-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silviacontrol', '0013_settingsmodel_k_p_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmodel',
            name='T_boiler',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='statusmodel',
            name='low_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statusmodel',
            name='m',
            field=models.FloatField(default=None, null=True),
        ),
    ]
