# Generated by Django 3.0.6 on 2020-10-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silviacontrol', '0014_auto_20201002_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='n_clean_cycles',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='t_clean_off',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='t_clean_on',
            field=models.IntegerField(default=10),
        ),
    ]
